### ISSUE TITLE
🚀 Feature Request: CI/CD + Docker + K3s Deployment for Health Dashboard

### ISSUE THREAD

**Issue by tuolden** [tuolden/health-dashboard#6]
# 🚀 Feature Request: CI/CD + Docker + K3s Deployment for Health Dashboard

## Summary

Set up automated build, test, and deployment pipelines for the **Health Dashboard** application. This includes:

- GitHub Actions workflow to lint, test, and build the app
- Dockerfile to containerize the frontend application
- Kubernetes manifests for deploying via ArgoCD to a local K3s cluster
- Ensure compatibility with local Docker registry `black:32003`

> ⚠️ No ConfigMap should be used — environment variables should be inlined directly.

---

## ✅ Acceptance Criteria

- [ ] GitHub Actions workflow builds app on push to `main`
- [ ] Docker image is tagged and pushed to local registry `black:32003/health-dashboard:latest`
- [ ] All K8s manifests live in `./kubernetes`
- [ ] ArgoCD `Application` correctly deploys from GitHub repo
- [ ] `Deployment` includes `env` inline (no ConfigMap)
- [ ] `Service` exposes container on port NOT being used 
- [ ] `Ingress` routes requests from `dashboard.home` and uses `dashboard-cert-tls`

---

### GitHub Actions: `.github/workflows/dashboard-ci.yml` or something VERY similar

```yaml
name: CI for Health Dashboard

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Remove existing image locally
        run: docker rmi -f black:32003/health-dashboard:latest || true

      - name: Build Docker image
        run: |
          docker buildx create --use || echo "builder exists"
          docker buildx build \
            --platform linux/amd64 \
            --load \
            -t health-dashboard:latest .

      - name: Tag and push to local registry
        run: |
          docker tag health-dashboard:latest black:32003/health-dashboard:latest
          docker push black:32003/health-dashboard:latest
```

---

### Dockerfile

Here is an inspiration file. Use it as inspiration.

```dockerfile
FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 5301
```

---

## 📦 Kubernetes Manifests (`./kubernetes/`)
Here is an inspiration file. Use it as inspiration.
### `application.yaml`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-dashboard
  namespace: argocd
spec:
  project: goal-app
  destination:
    namespace: goal-app
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/tuolden/health-dashboard.git'
    targetRevision: main
    path: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

---

### `deployment.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-dashboard
  namespace: goal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-dashboard
  template:
    metadata:
      labels:
        app: health-dashboard
    spec:
      containers:
        - name: dashboard
          image: black:32003/health-dashboard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5301
          env:
            - name: APP_ENV
              value: "production"
            - name: FORCE_REDEPLOY
              value: "v-2025-06-22"
```

---

### `service.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  name: health-dashboard-service
  namespace: goal-app
spec:
  type: ClusterIP
  selector:
    app: health-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5301
```

---

### `ingress.yaml`

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-dashboard-ingress
  namespace: goal-app
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
    - hosts:
        - dashboard.home
      secretName: dashboard-cert-tls
  rules:
    - host: dashboard.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: health-dashboard-service
                port:
                  number: 80
```
